script_path = "packages/registry/kernel/build-kernel.sh"
repo_url    = "https://github.com/brandonpayton/wasm-posix-kernel.git"
commit      = "8d76b33862c72b1565bbd377ad824ef214f50ab8"
revision    = 1

[binary]
index_url = "https://github.com/brandonpayton/wasm-posix-kernel/releases/download/binaries-abi-v{abi}/index.toml"
